//! AnnouncementRead DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AnnouncementRead;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AnnouncementRead
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAnnouncementReadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "announcement_id")]
    pub announcement_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "read_at")]
    pub read_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AnnouncementRead
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAnnouncementReadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "announcement_id")]
    pub announcement_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "user_id")]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "read_at")]
    pub read_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AnnouncementRead
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAnnouncementReadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "announcement_id")]
    pub announcement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_id")]
    pub user_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "read_at")]
    pub read_at: Option<DateTime<Utc>>,
}

impl PatchAnnouncementReadDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.announcement_id.is_some() || self.user_id.is_some() || self.read_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AnnouncementRead entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementReadResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub announcement_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub read_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AnnouncementRead entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementReadListResponseDto {
    /// List of items
    pub items: Vec<AnnouncementReadResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AnnouncementReadListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AnnouncementReadResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementReadSummaryDto {
    pub id: Uuid,
    pub announcement_id: Uuid,
    pub user_id: Uuid,
    pub read_at: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AnnouncementRead> for AnnouncementReadResponseDto {
    fn from(entity: AnnouncementRead) -> Self {
        Self {
            id: entity.id,
            announcement_id: entity.announcement_id,
            user_id: entity.user_id,
            read_at: entity.read_at,
            metadata: entity.metadata,
        }
    }
}

impl From<AnnouncementRead> for AnnouncementReadSummaryDto {
    fn from(entity: AnnouncementRead) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            announcement_id: entity.announcement_id,
            user_id: entity.user_id,
            read_at: entity.read_at,
            created_at,
        }
    }
}

impl From<CreateAnnouncementReadDto> for AnnouncementRead {
    fn from(dto: CreateAnnouncementReadDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            announcement_id: dto.announcement_id,
            user_id: dto.user_id,
            read_at: dto.read_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AnnouncementRead> for AnnouncementReadResponseDto {
    fn from(entity: &AnnouncementRead) -> Self {
        Self {
            id: entity.id.clone(),
            announcement_id: entity.announcement_id.clone(),
            user_id: entity.user_id.clone(),
            read_at: entity.read_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAnnouncementReadDto> for AnnouncementRead {
    fn from_create_dto(dto: CreateAnnouncementReadDto) -> backbone_core::ServiceResult<Self> {
        Ok(AnnouncementRead::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAnnouncementReadDto> for AnnouncementRead {
    fn apply_update(mut self, dto: UpdateAnnouncementReadDto) -> backbone_core::ServiceResult<Self> {
        self.announcement_id = dto.announcement_id;
        self.user_id = dto.user_id;
        self.read_at = dto.read_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AnnouncementRead here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
