//! Announcement DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Announcement;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AnnouncementAudienceType;
use crate::domain::entity::AnnouncementStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Announcement
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAnnouncementDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[serde(alias = "audience_type")]
    pub audience_type: AnnouncementAudienceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "audience_unit_id")]
    pub audience_unit_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "publish_from")]
    pub publish_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "publish_until")]
    pub publish_until: Option<DateTime<Utc>>,
    pub status: AnnouncementStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub pinned: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "targeted_count")]
    pub targeted_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Announcement
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAnnouncementDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[serde(alias = "audience_type")]
    pub audience_type: AnnouncementAudienceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "audience_unit_id")]
    pub audience_unit_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "publish_from")]
    pub publish_from: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "publish_until")]
    pub publish_until: Option<DateTime<Utc>>,
    pub status: AnnouncementStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub pinned: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "targeted_count")]
    pub targeted_count: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Announcement
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAnnouncementDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "audience_type")]
    pub audience_type: Option<AnnouncementAudienceType>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "audience_unit_id")]
    pub audience_unit_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "publish_from")]
    pub publish_from: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "publish_until")]
    pub publish_until: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<AnnouncementStatus>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pinned: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "targeted_count")]
    pub targeted_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

impl PatchAnnouncementDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.title.is_some() || self.body.is_some() || self.audience_type.is_some() || self.audience_unit_id.is_some() || self.publish_from.is_some() || self.publish_until.is_some() || self.status.is_some() || self.pinned.is_some() || self.targeted_count.is_some() || self.created_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Announcement entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub audience_type: AnnouncementAudienceType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub audience_unit_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub publish_from: DateTime<Utc>,
    pub publish_until: Option<DateTime<Utc>>,
    pub status: AnnouncementStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub pinned: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub targeted_count: i32,
    pub created_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Announcement entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementListResponseDto {
    /// List of items
    pub items: Vec<AnnouncementResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AnnouncementListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AnnouncementResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AnnouncementSummaryDto {
    pub id: Uuid,
    pub title: String,
    pub body: String,
    pub audience_type: AnnouncementAudienceType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Announcement> for AnnouncementResponseDto {
    fn from(entity: Announcement) -> Self {
        Self {
            id: entity.id,
            title: entity.title,
            body: entity.body,
            audience_type: entity.audience_type,
            audience_unit_id: entity.audience_unit_id,
            publish_from: entity.publish_from,
            publish_until: entity.publish_until,
            status: entity.status,
            pinned: entity.pinned,
            targeted_count: entity.targeted_count,
            created_by: entity.created_by,
            metadata: entity.metadata,
        }
    }
}

impl From<Announcement> for AnnouncementSummaryDto {
    fn from(entity: Announcement) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            title: entity.title,
            body: entity.body,
            audience_type: entity.audience_type,
            created_at,
        }
    }
}

impl From<CreateAnnouncementDto> for Announcement {
    fn from(dto: CreateAnnouncementDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            title: dto.title,
            body: dto.body,
            audience_type: dto.audience_type,
            audience_unit_id: dto.audience_unit_id,
            publish_from: dto.publish_from,
            publish_until: dto.publish_until,
            status: dto.status,
            pinned: dto.pinned,
            targeted_count: dto.targeted_count,
            created_by: dto.created_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Announcement> for AnnouncementResponseDto {
    fn from(entity: &Announcement) -> Self {
        Self {
            id: entity.id.clone(),
            title: entity.title.clone(),
            body: entity.body.clone(),
            audience_type: entity.audience_type.clone(),
            audience_unit_id: entity.audience_unit_id.clone(),
            publish_from: entity.publish_from.clone(),
            publish_until: entity.publish_until.clone(),
            status: entity.status.clone(),
            pinned: entity.pinned.clone(),
            targeted_count: entity.targeted_count.clone(),
            created_by: entity.created_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAnnouncementDto> for Announcement {
    fn from_create_dto(dto: CreateAnnouncementDto) -> backbone_core::ServiceResult<Self> {
        Ok(Announcement::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAnnouncementDto> for Announcement {
    fn apply_update(mut self, dto: UpdateAnnouncementDto) -> backbone_core::ServiceResult<Self> {
        self.title = dto.title;
        self.body = dto.body;
        self.audience_type = dto.audience_type;
        self.audience_unit_id = dto.audience_unit_id;
        self.publish_from = dto.publish_from;
        self.publish_until = dto.publish_until;
        self.status = dto.status;
        self.pinned = dto.pinned;
        self.targeted_count = dto.targeted_count;
        self.created_by = dto.created_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Announcement here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
