//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod announcement_domain_policy;
pub mod announcement_read_domain_policy;

pub use announcement_domain_policy::AnnouncementDomainPolicy;
pub use announcement_read_domain_policy::AnnouncementReadDomainPolicy;

// <<< CUSTOM
// END CUSTOM
