//! Application service for AnnouncementRead entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `announcement_read_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAnnouncementReadDto, UpdateAnnouncementReadDto};
use crate::domain::entity::AnnouncementRead;
use crate::infrastructure::persistence::AnnouncementReadRepository;

/// Application service for AnnouncementRead entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `announcement_read_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AnnouncementReadServiceCustom {
///     inner: Arc<AnnouncementReadService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AnnouncementReadService = GenericCrudService<
    AnnouncementRead,
    CreateAnnouncementReadDto,
    UpdateAnnouncementReadDto,
    AnnouncementReadRepository,
>;

// <<< CUSTOM
// END CUSTOM
