//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod announcement_service;
pub mod announcement_read_service;

// <<< CUSTOM
pub mod announcement_events;
pub mod announcement_write_service;
// END CUSTOM

pub use announcement_service::AnnouncementService;
pub use announcement_read_service::AnnouncementReadService;
// <<< CUSTOM
pub use announcement_events::{AnnouncementEvent, AnnouncementEventSink, LoggingSink};
pub use announcement_write_service::{
    AnnouncementError, AnnouncementWriteService, NewAnnouncement, PublishOutcome,
};
// END CUSTOM
