-- Announcement Seed Data
-- Generated by metaphor-schema
--
-- SEED: none — announcements are tenant content, never global reference data.
-- Customize this file to add your initial data.

-- INSERT INTO announcements.announcements (
--     id,
--     title,
--     body,
--     audience_type,
--     audience_unit_id,
--     publish_from,
--     publish_until,
--     status,
--     pinned,
--     targeted_count,
--     created_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO announcements.announcements (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

