-- AnnouncementRead Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the announcements.announcement_reads table.
-- Customize this file to add your initial data.

-- INSERT INTO announcements.announcement_reads (
--     id,
--     announcement_id,
--     user_id,
--     read_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO announcements.announcement_reads (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

