-- Migration: Create announcement_reads table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS announcements;

CREATE TABLE IF NOT EXISTS announcements.announcement_reads (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    announcement_id UUID NOT NULL,
    user_id UUID NOT NULL,
    read_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_announcement_reads_announcement_id_user_id ON announcements.announcement_reads (announcement_id, user_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_announcement_reads_metadata_gin ON announcements.announcement_reads USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_announcement_reads_metadata_deleted_at ON announcements.announcement_reads ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_announcement_reads_metadata_created_at ON announcements.announcement_reads ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_announcement_reads_metadata_updated_at ON announcements.announcement_reads ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION announcements.announcement_reads_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS announcement_reads_insert_audit ON announcements.announcement_reads;
CREATE TRIGGER announcement_reads_insert_audit BEFORE INSERT ON announcements.announcement_reads
    FOR EACH ROW EXECUTE FUNCTION announcements.announcement_reads_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS announcement_reads_update_audit ON announcements.announcement_reads;
CREATE TRIGGER announcement_reads_update_audit BEFORE UPDATE ON announcements.announcement_reads
    FOR EACH ROW EXECUTE FUNCTION announcements.announcement_reads_audit_timestamp();
