-- Enum types for notification module
-- Generated by metaphor-schema

-- Create announcement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'announcement_status') THEN
        CREATE TYPE announcement_status AS ENUM ('draft', 'scheduled', 'published', 'archived');
    END IF;
END
$$;

-- Create announcement_audience_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'announcement_audience_type') THEN
        CREATE TYPE announcement_audience_type AS ENUM ('company', 'branch', 'department');
    END IF;
END
$$;

