-- Migration: Create announcements table
-- Generated by metaphor-schema

-- Create announcement_audience_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'announcement_audience_type') THEN
        CREATE TYPE announcement_audience_type AS ENUM ('company', 'branch', 'department');
    END IF;
END
$$;

-- Create announcement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'announcement_status') THEN
        CREATE TYPE announcement_status AS ENUM ('draft', 'scheduled', 'published', 'archived');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS announcements;

CREATE TABLE IF NOT EXISTS announcements.announcements (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    audience_type announcement_audience_type NOT NULL,
    audience_unit_id UUID NOT NULL,
    publish_from TIMESTAMPTZ NOT NULL,
    publish_until TIMESTAMPTZ,
    status announcement_status NOT NULL DEFAULT 'draft',
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    targeted_count INTEGER NOT NULL DEFAULT 0,
    created_by UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_announcements_status_publish_from ON announcements.announcements (status, publish_from);

CREATE INDEX IF NOT EXISTS idx_announcements_audience_unit_id ON announcements.announcements (audience_unit_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_announcements_metadata_gin ON announcements.announcements USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_announcements_metadata_deleted_at ON announcements.announcements ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_announcements_metadata_created_at ON announcements.announcements ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_announcements_metadata_updated_at ON announcements.announcements ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION announcements.announcements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS announcements_insert_audit ON announcements.announcements;
CREATE TRIGGER announcements_insert_audit BEFORE INSERT ON announcements.announcements
    FOR EACH ROW EXECUTE FUNCTION announcements.announcements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS announcements_update_audit ON announcements.announcements;
CREATE TRIGGER announcements_update_audit BEFORE UPDATE ON announcements.announcements
    FOR EACH ROW EXECUTE FUNCTION announcements.announcements_audit_timestamp();
