//! Domain events for AnnouncementRead entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AnnouncementRead;

/// Domain events for AnnouncementRead — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AnnouncementRead>)` variant.
pub type AnnouncementReadEvent = CrudEvent<AnnouncementRead>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AnnouncementRead events.
pub type AnnouncementReadEventPublisher = Arc<dyn CrudEventPublisher<AnnouncementRead> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAnnouncementReadEventPublisher = NoOpCrudEventPublisher<AnnouncementRead>;
