//! Event handler trait for Announcement events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AnnouncementEvent;

/// Event handler for Announcement events.
/// Implement this trait to react to Announcement lifecycle events.
pub trait AnnouncementEventHandler: EventHandler<AnnouncementEvent> {}
