//! Domain events for Announcement entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Announcement;

/// Domain events for Announcement — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Announcement>)` variant.
pub type AnnouncementEvent = CrudEvent<Announcement>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Announcement events.
pub type AnnouncementEventPublisher = Arc<dyn CrudEventPublisher<Announcement> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAnnouncementEventPublisher = NoOpCrudEventPublisher<Announcement>;
