//! Event handler trait for AnnouncementRead events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AnnouncementReadEvent;

/// Event handler for AnnouncementRead events.
/// Implement this trait to react to AnnouncementRead lifecycle events.
pub trait AnnouncementReadEventHandler: EventHandler<AnnouncementReadEvent> {}
