//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod announcement_events;
pub mod announcement_event_handlers;
pub mod announcement_read_events;
pub mod announcement_read_event_handlers;

pub use announcement_events::{AnnouncementEvent, AnnouncementEventPublisher, NoopAnnouncementEventPublisher};
pub use announcement_event_handlers::AnnouncementEventHandler;
pub use announcement_read_events::{AnnouncementReadEvent, AnnouncementReadEventPublisher, NoopAnnouncementReadEventPublisher};
pub use announcement_read_event_handlers::AnnouncementReadEventHandler;

// <<< CUSTOM
// END CUSTOM
