//! Announcements Integration Layer (Anti-Corruption Layer)
//!
//! Generated by metaphor-schema. Do not edit manually.

pub use backbone_core::{ModuleAdapter, ProjectionAdapter, IntegrationError};
pub use backbone_messaging::SubscriberRegistry;

// <<< CUSTOM
// END CUSTOM
