//! Repository trait for Announcement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Announcement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Announcement, AnnouncementAudienceType, AnnouncementStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AnnouncementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AnnouncementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AnnouncementPaginatedResult {
    pub data: Vec<Announcement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AnnouncementFilter {
    pub title: Option<String>,
    pub body: Option<String>,
    pub audience_type: Option<AnnouncementAudienceType>,
    pub audience_unit_id: Option<Uuid>,
    pub status: Option<AnnouncementStatus>,
    pub pinned: Option<bool>,
}

impl AnnouncementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.title.is_some() || self.body.is_some() || self.audience_type.is_some() || self.audience_unit_id.is_some() || self.status.is_some() || self.pinned.is_some()
    }
}

/// Repository trait for Announcement aggregate
///
/// This trait defines the persistence contract for Announcement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AnnouncementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new announcement entity
    async fn save(&self, entity: &Announcement) -> Result<Announcement>;

    /// Find announcement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Announcement>>;

    /// Find all announcement entities
    async fn find_all(&self) -> Result<Vec<Announcement>>;

    /// Update announcement by ID
    async fn update(&self, id: &str, entity: &Announcement) -> Result<Option<Announcement>>;

    /// Delete announcement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List announcement with pagination
    async fn list(&self, params: AnnouncementPaginationParams) -> Result<AnnouncementPaginatedResult>;

    /// List announcement with pagination and filters
    async fn list_with_filters(&self, params: AnnouncementPaginationParams, filters: AnnouncementFilter) -> Result<AnnouncementPaginatedResult>;

    /// Count all announcement entities
    async fn count(&self) -> Result<u64>;

    /// Count announcement entities matching filters
    async fn count_with_filters(&self, filters: AnnouncementFilter) -> Result<u64>;

    /// Check if announcement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete announcement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted announcement by ID
    async fn restore(&self, id: &str) -> Result<Option<Announcement>>;

    /// List soft-deleted announcement entities
    async fn list_deleted(&self, params: AnnouncementPaginationParams) -> Result<AnnouncementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save announcement entities
    async fn bulk_save(&self, entities: &[Announcement]) -> Result<Vec<Announcement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
