//! Repository trait for AnnouncementRead aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AnnouncementRead aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::AnnouncementRead;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AnnouncementReadPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AnnouncementReadPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AnnouncementReadPaginatedResult {
    pub data: Vec<AnnouncementRead>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AnnouncementReadFilter {
    pub announcement_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
}

impl AnnouncementReadFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.announcement_id.is_some() || self.user_id.is_some()
    }
}

/// Repository trait for AnnouncementRead aggregate
///
/// This trait defines the persistence contract for AnnouncementRead entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AnnouncementReadRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new announcement_read entity
    async fn save(&self, entity: &AnnouncementRead) -> Result<AnnouncementRead>;

    /// Find announcement_read by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AnnouncementRead>>;

    /// Find all announcement_read entities
    async fn find_all(&self) -> Result<Vec<AnnouncementRead>>;

    /// Update announcement_read by ID
    async fn update(&self, id: &str, entity: &AnnouncementRead) -> Result<Option<AnnouncementRead>>;

    /// Delete announcement_read by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List announcement_read with pagination
    async fn list(&self, params: AnnouncementReadPaginationParams) -> Result<AnnouncementReadPaginatedResult>;

    /// List announcement_read with pagination and filters
    async fn list_with_filters(&self, params: AnnouncementReadPaginationParams, filters: AnnouncementReadFilter) -> Result<AnnouncementReadPaginatedResult>;

    /// Count all announcement_read entities
    async fn count(&self) -> Result<u64>;

    /// Count announcement_read entities matching filters
    async fn count_with_filters(&self, filters: AnnouncementReadFilter) -> Result<u64>;

    /// Check if announcement_read exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete announcement_read by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted announcement_read by ID
    async fn restore(&self, id: &str) -> Result<Option<AnnouncementRead>>;

    /// List soft-deleted announcement_read entities
    async fn list_deleted(&self, params: AnnouncementReadPaginationParams) -> Result<AnnouncementReadPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save announcement_read entities
    async fn bulk_save(&self, entities: &[AnnouncementRead]) -> Result<Vec<AnnouncementRead>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
