//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod announcement_repository;
pub mod announcement_read_repository;

// Re-exports
pub use announcement_repository::{
    AnnouncementRepository,
    AnnouncementPaginationParams,
    AnnouncementPaginatedResult,
    AnnouncementFilter,
};
pub use announcement_read_repository::{
    AnnouncementReadRepository,
    AnnouncementReadPaginationParams,
    AnnouncementReadPaginatedResult,
    AnnouncementReadFilter,
};
