//! Validator for AnnouncementRead entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AnnouncementRead>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::AnnouncementRead;

/// Validator type alias for AnnouncementRead entities.
pub type AnnouncementReadValidator = EntityValidator<AnnouncementRead>;

/// Build a validator for AnnouncementRead with all schema-defined field rules.
pub fn announcement_read_validator() -> AnnouncementReadValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
