//! Validator for Announcement entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Announcement>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Announcement;

/// Validator type alias for Announcement entities.
pub type AnnouncementValidator = EntityValidator<Announcement>;

/// Build a validator for Announcement with all schema-defined field rules.
pub fn announcement_validator() -> AnnouncementValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &Announcement| &e.title))
        .rule(RequiredString::new("body", |e: &Announcement| &e.body))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
