//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod announcement_validator;
pub mod announcement_read_validator;

pub use announcement_validator::{AnnouncementValidator, announcement_validator};
pub use announcement_read_validator::{AnnouncementReadValidator, announcement_read_validator};

// <<< CUSTOM
// END CUSTOM
