//! Announcement API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Announcement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ANNOUNCEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Announcement
pub struct AnnouncementTestData;

impl TestDataGenerator for AnnouncementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "audience_type": "company",
            "audience_unit_id": Uuid::new_v4().to_string(),
            "publish_from": now,
            "publish_until": null,
            "status": "draft",
            "pinned": false,
            "targeted_count": 1,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "audience_type": "company",
            "audience_unit_id": Uuid::new_v4().to_string(),
            "publish_from": now,
            "publish_until": null,
            "status": "draft",
            "pinned": false,
            "targeted_count": 1,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ANNOUNCEMENT API TEST
// ============================================================================

/// Announcement API test suite
pub struct AnnouncementApiTest {
    inner: GenericCrudTest<AnnouncementTestData>,
}

impl AnnouncementApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/announcements", "Announcement");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AnnouncementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AnnouncementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_announcement_crud() {
        let mut test = AnnouncementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Announcement specific tests here
// <<< CUSTOM TESTS END >>>
