//! AnnouncementRead API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AnnouncementRead CRUD API endpoints.

use chrono::Utc;
use crate::integration::framework::ApiTest;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ANNOUNCEMENTREAD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AnnouncementRead
pub struct AnnouncementReadTestData;

impl TestDataGenerator for AnnouncementReadTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "announcement_id": Uuid::new_v4().to_string(),
            "user_id": Uuid::new_v4().to_string(),
            "read_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "announcement_id": Uuid::new_v4().to_string(),
            "user_id": Uuid::new_v4().to_string(),
            "read_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/announcements", &super::announcement_api_test::AnnouncementTestData).await {
            deps.push(("announcement_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ANNOUNCEMENTREAD API TEST
// ============================================================================

/// AnnouncementRead API test suite
pub struct AnnouncementReadApiTest {
    inner: GenericCrudTest<AnnouncementReadTestData>,
}

impl AnnouncementReadApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/announcement_reads", "AnnouncementRead");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AnnouncementReadTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AnnouncementReadApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_announcement_read_crud() {
        let mut test = AnnouncementReadApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AnnouncementRead specific tests here
// <<< CUSTOM TESTS END >>>
