//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod announcement_api_test;
pub mod announcement_read_api_test;

// Re-exports for convenience
pub use announcement_api_test::*;
pub use announcement_read_api_test::*;
