//! Announcements Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AnnouncementService;
use crate::application::service::AnnouncementReadService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Announcement service
    pub announcement_service: Arc<AnnouncementService>,
    /// AnnouncementRead service
    pub announcement_read_service: Arc<AnnouncementReadService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        announcement_service: Arc<AnnouncementService>,
        announcement_read_service: Arc<AnnouncementReadService>
    ) -> Self {
        Self {
            announcement_service,
            announcement_read_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AnnouncementsModule) -> Self {
        Self {
            announcement_service: module.announcement_service.clone(),
            announcement_read_service: module.announcement_read_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    announcement_service: Option<Arc<AnnouncementService>>,
    announcement_read_service: Option<Arc<AnnouncementReadService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Announcement service.
    pub fn with_announcement_service(mut self, service: Arc<AnnouncementService>) -> Self {
        self.announcement_service = Some(service);
        self
    }

    /// Set the AnnouncementRead service.
    pub fn with_announcement_read_service(mut self, service: Arc<AnnouncementReadService>) -> Self {
        self.announcement_read_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            announcement_service: self.announcement_service.expect("announcement_service is required"),
            announcement_read_service: self.announcement_read_service.expect("announcement_read_service is required"),
        }
    }
}
