//! Public events for Announcements module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ANNOUNCEMENT EVENTS
// ============================================================================

/// Event published when a Announcement is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementCreatedEvent {
    pub id: AnnouncementId,
    pub data: AnnouncementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Announcement is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementUpdatedEvent {
    pub id: AnnouncementId,
    pub data: AnnouncementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Announcement is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementDeletedEvent {
    pub id: AnnouncementId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ANNOUNCEMENTREAD EVENTS
// ============================================================================

/// Event published when a AnnouncementRead is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadCreatedEvent {
    pub id: AnnouncementReadId,
    pub data: AnnouncementReadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AnnouncementRead is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadUpdatedEvent {
    pub id: AnnouncementReadId,
    pub data: AnnouncementReadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AnnouncementRead is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadDeletedEvent {
    pub id: AnnouncementReadId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Announcements module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AnnouncementsEvent {
    AnnouncementCreated(AnnouncementCreatedEvent),
    AnnouncementUpdated(AnnouncementUpdatedEvent),
    AnnouncementDeleted(AnnouncementDeletedEvent),
    AnnouncementReadCreated(AnnouncementReadCreatedEvent),
    AnnouncementReadUpdated(AnnouncementReadUpdatedEvent),
    AnnouncementReadDeleted(AnnouncementReadDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementsEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for AnnouncementsEventMetadata {
    fn default() -> Self {
        Self {
            module: "announcements",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
