//! Announcements Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Announcements exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use announcements::exports::{AnnouncementDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AnnouncementDto` - Data transfer object for Announcement
/// - `AnnouncementSummary` - Summary view of Announcement
/// - `AnnouncementId` - Type-safe ID wrapper
/// - `AnnouncementReadDto` - Data transfer object for AnnouncementRead
/// - `AnnouncementReadSummary` - Summary view of AnnouncementRead
/// - `AnnouncementReadId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `AnnouncementCreatedEvent` - Published when Announcement is created
/// - `AnnouncementUpdatedEvent` - Published when Announcement is updated
/// - `AnnouncementDeletedEvent` - Published when Announcement is deleted
/// - `AnnouncementReadCreatedEvent` - Published when AnnouncementRead is created
/// - `AnnouncementReadUpdatedEvent` - Published when AnnouncementRead is updated
/// - `AnnouncementReadDeletedEvent` - Published when AnnouncementRead is deleted
pub struct ExportSummary;
