//! Public types for Announcement module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// ANNOUNCEMENT TYPES
// ============================================================================

/// Type-safe ID for Announcement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AnnouncementId(pub Uuid);

impl AnnouncementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AnnouncementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AnnouncementId> for Uuid {
    fn from(id: AnnouncementId) -> Self {
        id.0
    }
}

/// Data transfer object for Announcement
///
/// This is the public representation of Announcement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementDto {
    pub id: AnnouncementId,
    pub title: String,
    pub body: String,
    pub audience_type: AnnouncementAudienceType,
    pub audience_unit_id: Uuid,
    pub publish_from: DateTime<Utc>,
    pub publish_until: Option<DateTime<Utc>>,
    pub status: AnnouncementStatus,
    pub pinned: bool,
    pub targeted_count: i32,
    pub created_by: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Announcement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementSummary {
    pub id: AnnouncementId,
    pub title: String,
    pub status: AnnouncementStatus,
}

/// Reference to Announcement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementRef {
    pub id: AnnouncementId,
}

// ============================================================================
// ANNOUNCEMENTREAD TYPES
// ============================================================================

/// Type-safe ID for AnnouncementRead
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AnnouncementReadId(pub Uuid);

impl AnnouncementReadId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AnnouncementReadId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AnnouncementReadId> for Uuid {
    fn from(id: AnnouncementReadId) -> Self {
        id.0
    }
}

/// Data transfer object for AnnouncementRead
///
/// This is the public representation of AnnouncementRead for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadDto {
    pub id: AnnouncementReadId,
    pub announcement_id: Uuid,
    pub user_id: Uuid,
    pub read_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of AnnouncementRead for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadSummary {
    pub id: AnnouncementReadId,
}

/// Reference to AnnouncementRead for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnnouncementReadRef {
    pub id: AnnouncementReadId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
