//! Announcements Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;
// <<< CUSTOM MODULES
pub mod request_pool;
// END CUSTOM

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AnnouncementService;
pub use application::service::AnnouncementReadService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Announcements module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let announcements = AnnouncementsModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = announcements.all_crud_routes();
/// ```
pub struct AnnouncementsModule {
    pub(crate) announcement_service: Arc<AnnouncementService>,
    pub(crate) announcement_read_service: Arc<AnnouncementReadService>,
    // <<< CUSTOM FIELDS
    /// The validated write engine — the lifecycle verbs (schedule / publish /
    /// archive) and the read-mark upsert. Generic CRUD on an announcement row
    /// bypasses the status machine; use this for every state change.
    pub(crate) write_service: Arc<application::service::AnnouncementWriteService>,
    // END CUSTOM
}

impl AnnouncementsModule {
    /// Create a new module builder
    pub fn builder() -> AnnouncementsModuleBuilder {
        AnnouncementsModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_announcement_routes,
        };

        Router::new()
            .merge(create_announcement_routes(self.announcement_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_announcement_read_routes,
        };

        Router::new()
            .merge(create_announcement_read_routes(self.announcement_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated write engine (schedule / publish / archive, read-mark).
    pub fn write_service(&self) -> Arc<application::service::AnnouncementWriteService> {
        self.write_service.clone()
    }

    /// The recommended production surface: read-only CRUD for both entities +
    /// the guarded verb routes (draft create/update stay generic writes on a
    /// draft row; schedule/publish/archive and the read mark go through the
    /// write service only).
    pub fn guarded_routes(&self) -> Router {
        use presentation::http::guarded_routes::create_guarded_announcement_routes;

        Router::new()
            .merge(self.readonly_routes())
            .merge(create_guarded_announcement_routes(self.write_service.clone()))
    }
    // END CUSTOM
}

/// Builder for AnnouncementsModule
pub struct AnnouncementsModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM BUILDER FIELDS
    // END CUSTOM
}

impl AnnouncementsModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM BUILDER DEFAULTS
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AnnouncementsModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Announcement service
        let announcement_repository = Arc::new(AnnouncementRepository::new(db_pool.clone()));
        let announcement_service = Arc::new(AnnouncementService::with_repository(announcement_repository.clone()));

        // AnnouncementRead service
        let announcement_read_repository = Arc::new(AnnouncementReadRepository::new(db_pool.clone()));
        let announcement_read_service = Arc::new(AnnouncementReadService::with_repository(announcement_read_repository.clone()));

        // <<< CUSTOM
        // The validated write engine. Self-constructs from the pool; the event
        // sink stays per-call (the composing service's concern).
        let write_service = Arc::new(application::service::AnnouncementWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(AnnouncementsModule {
            announcement_service,
            announcement_read_service,
            // <<< CUSTOM
            write_service,
            // END CUSTOM
        })
    }
}

impl Default for AnnouncementsModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
