//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod announcement_handler;
pub mod announcement_read_handler;

pub mod guarded_routes;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use announcement_handler::{create_announcement_routes, create_announcement_read_routes, create_announcement_write_routes};
pub use announcement_read_handler::{create_announcement_read_routes as create_announcement_read_ledger_routes, create_announcement_read_read_routes as create_announcement_read_ledger_read_routes, create_announcement_read_write_routes as create_announcement_read_ledger_write_routes};
// <<< CUSTOM
// END CUSTOM
