//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod announcement_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use announcement_handler::{create_announcement_routes, create_announcement_read_routes, create_announcement_write_routes};
// <<< CUSTOM
// END CUSTOM
